### ISSUE TITLE
It doesn't work with archived petitions

### ISSUE THREAD

**Issue by h-lame** [unboxed/petition-map#24]
It doesn't make any sense for the archived petitions from the original petitions site (id < 10,000) (2010-2015 Conservative + Lib Dem coalition govt.) because they don't have any data about signatures by constituency, but the ones from the new site (10,001 < id < 20,000) (2015-2017 Conservative govt.) will work because they do have the data.

I haven't checked if it doesn't work just because the URL format is different and we're being explicit about what urls we'll try to pull json from (we should be!) or if somehow the data response is different and it breaks.

**Comment by pixeltrix** [comment]
Fixed by #27 and alphagov/e-petitions#663
